# Learning Machine Learning 




## Data Preprocessing Tools CH_03

#### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#### Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, 1:3].values.astype(str)
# pd.set_option('display.float_format')
y = dataset.iloc[:, -1].values
print(X)
print(y)

[['44.0' '72000.0']
 ['27.0' '48000.0']
 ['30.0' '54000.0']
 ['38.0' '61000.0']
 ['40.0' 'nan']
 ['35.0' '58000.0']
 ['nan' '52000.0']
 ['48.0' '79000.0']
 ['50.0' '83000.0']
 ['37.0' '67000.0']]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


#### Taking care of missing data

In [3]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)


[['44.0' '72000.0']
 ['27.0' '48000.0']
 ['30.0' '54000.0']
 ['38.0' '61000.0']
 ['40.0' '63777.77777777778']
 ['35.0' '58000.0']
 ['nan' '52000.0']
 ['48.0' '79000.0']
 ['50.0' '83000.0']
 ['37.0' '67000.0']]


#### Encoding categorical data

In [4]:
# for country variable
from sklearn.preprocessing import LabelEncoder
label_encoder_X = LabelEncoder()
X[:,0] = label_encoder_X.fit_transform(X[:,0])
print(X)

[['6' '72000.0']
 ['0' '48000.0']
 ['1' '54000.0']
 ['4' '61000.0']
 ['5' '63777.77777777778']
 ['2' '58000.0']
 ['9' '52000.0']
 ['7' '79000.0']
 ['8' '83000.0']
 ['3' '67000.0']]


#### Encoding the Independent Variable

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

  (0, 6)	1.0
  (0, 10)	72000.0
  (1, 0)	1.0
  (1, 10)	48000.0
  (2, 1)	1.0
  (2, 10)	54000.0
  (3, 4)	1.0
  (3, 10)	61000.0
  (4, 5)	1.0
  (4, 10)	63777.77777777778
  (5, 2)	1.0
  (5, 10)	58000.0
  (6, 9)	1.0
  (6, 10)	52000.0
  (7, 7)	1.0
  (7, 10)	79000.0
  (8, 8)	1.0
  (8, 10)	83000.0
  (9, 3)	1.0
  (9, 10)	67000.0


/opt/anaconda3/lib/python3.9/site-packages/sklearn/compose/_column_transformer.py:779: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  check_array(X, accept_sparse=True, force_all_finite=False)


#### Encoding the dependent variable

In [6]:
# le = LabelEncoder()
y = LabelEncoder().fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


#### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=1)
print(X_test)


TypeError: Singleton array array(<10x11 sparse matrix of type '<class 'numpy.float64'>'
	with 20 stored elements in Compressed Sparse Row format>, dtype=object) cannot be considered a valid collection.

##### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.fit_transform(X_test[:,3:])

print(X_train)
print(X_test)


[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]


In [8]:
from sklearn import linear_model